name: HTML Structure Check

on:
  push:
  pull_request:

jobs:
  check-html-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for HTML, CSS, and JS files
        run: |
          echo "Listing HTML, CSS, and JS files:"
          ls *.html *.css *.js || echo "Some files are missing"
          echo "✅ Workflow ran successfully."
